#!/bin/bash
# Installer for dotfiles initializers

sudo rm /usr/share/sddm/themes/abstractdark/Main.qml -v
sudo rm /etc/sddm.conf -v
sudo cp ~/dotfiles/sddm/Main.qml /usr/share/sddm/themes/abstractdark/Main.qml -v
sudo cp ~/dotfiles/sddm/sddm.conf /etc/sddm.conf -v
