#!/bin/bash

# Dotfiles Update
# Author: Kenneth Haynie
# Last Updated: 4/4/2020


# Code for automatically updating dotfiles and awesome, terminal, and sddm
# configs

cd $HOME/.config/dotfiles
git pull -v
$HOME/.config/dotfiles/scripts/updateSDDM -v
cd $HOME/.config/awesome
git pull -v
