#!/bin/bash
# Required for updating SDDM customizations 

sudo rm /usr/share/sddm/themes/abstractdark/Main.qml -v
sudo rm /etc/sddm.conf -v
sudo cp $HOME/.config/dotfiles/sddm/Main.qml /usr/share/sddm/themes/abstractdark/Main.qml -v
sudo cp $HOME/.config/dotfiles/sddm/sddm.conf /etc/sddm.conf -v
